{{- define "kafka-app.configmap" -}}
{{ if .Values.files }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-app.fullname" . }}
  {{- include "kafka-app.annotations" . }}
  labels:
    {{- include "kafka-app.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.labels }}
    {{ $key | quote }}: {{ $value | quote }}
    {{- end }}
data:
  {{- range $key, $value := .Values.files }}
  {{ $key }}: {{ $value.content | quote }}
  {{- end }}
{{ end }}
{{- end -}}
