{{- define "producer-app.jobSpec" -}}
{{- if .Values.ttlSecondsAfterFinished }}
ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }}
{{- end }}
template:
{{ include "producer-app.podTemplate" . | indent 2 }}
backoffLimit: {{ .Values.backoffLimit }}
{{- end -}}
