nameOverride: bakdata-rclone-copy

# This is the cofiguration for the specific rclone-cronjob that you want to run.
# `sync` contains the config for the source and destination of the rclone copy job.
# It can be interpreted as:
# rclone copy {source.name}:{source.path} {dest.name}:{dest.path}
sync:
  source:
    # This is the name for the source remote from the rclone.conf file.
    # If the value specified here is not present in the config file, the job will fail.
    # See rclone.conf.template for an example.
    name: my-sftp

    # This is the path to the source directory.
    path: /tmp/sync-dir

  dest:
    # This is the name for the destination remote from the rclone.conf file.
    # If the value specified here is not present in the config file, the job will fail.
    # See rclone.conf.template for an example.
    name: my-s3

    # This is the path to the target directory.
    path: my-s3-bucket

# Additional arguments to pass to rclone. 
# The expected value is an array with comma seperated flag and value passed as a string. 
# Example: ["--transfers", '"1"']
arguments: []

# Pattern of files to copy. Standard UNIX file glob patterns are used. Default: "*"
# See templates/include-pattern-config.yaml for more details on usage in ConfigMap.
includePattern: "*"

# Cron schedule for this connect job. Default is at 12:00 every day.
schedule: "0 12 * * *"

suspend: false

# Content of the rclone.conf file.
rcloneConf: ""

# AWS Role to be used in this Docker image.
awsRole: ""

# Release version for the openbridge/ob_bulkstash docker image.
# You probably don't need to change this.
imageRelease: 1.53.1

restartPolicy: OnFailure

# serviceAccountName: foo

tolerations: []
#   - key: "foo"
#     operator: "Exists"
#     effect: "NoSchedule"
#   - key: "bar"
#     operator: "Exists"
#     effect: "NoSchedule"

nodeAffinity: {}
#   requiredDuringSchedulingIgnoredDuringExecution:
#     nodeSelectorTerms:
#     - matchExpressions:
#       - key: foo
#         operator: In
#         values:
#         - bar
#         - baz
#   preferredDuringSchedulingIgnoredDuringExecution:
#   - weight: 1
#     preference:
#       matchExpressions:
#       - key: foo
#         operator: In
#         values:
#         - bar
#         - baz

resources:
  requests:
    cpu: 200m
    memory: 300Mi
  limits:
    memory: 2G
    cpu: 500m

successfulJobsHistoryLimit: 1
failedJobsHistoryLimit: 1
backoffLimit: 6
