apiVersion: v1
name: consumerproducer-app
description: A helm chart for deploying a Kafka consumerproducer application based on the bakdata KafkaConsumerProducerApplication template.
version: 0.1.0
maintainers:
  - name: bakdata
    email: opensource@bakdata.com
    url: bakdata.com
