apiVersion: v2
name: streams-app
description: A helm chart for deploying a kafka streams application based on the bakdata KafkaStreamsApplication template.
version: 0.2.0
dependencies:
  - name: common-app
    version: "0.1.0"
    repository: "file://../common-app"
