apiVersion: v2
name: kafka-app
description: A common library chart for Kafka applications.
type: library
version: 0.1.0
appVersion: "0.1.0"
maintainers:
  - name: bakdata
    email: opensource@bakdata.com
    url: bakdata.com
