apiVersion: v2
name: streams-app-cleanup-job
description: A helm chart for deploying a kafka streams application based on the bakdata KafkaStreamsApplication template.
version: 0.2.0
maintainers:
  - name: bakdata
    email: opensource@bakdata.com
    url: bakdata.com
dependencies:
  - name: common-app
    version: "0.1.0"
    repository: "file://../common-app"
