apiVersion: v2
name: consumer-app-cleanup-job
description: A helm chart for deploying a clean up job for a Kafka consumer application.
version: 0.2.0
maintainers:
  - name: bakdata
    email: opensource@bakdata.com
    url: bakdata.com
dependencies:
  - name: kafka-app
    version: "0.1.0"
    repository: "file://../kafka-app"
