{{- if and .Values.persistence.enabled (not .Values.persistence.size) }}
{{- fail "When persistence is enabled, you must set .Values.persistence.size" }}
{{- end }}

{{- include "kafka-app.deployment" . }}
spec:
{{- include "kafka-app.deployment-spec" . }}
  template:
    metadata:
    {{- include "kafka-app.pod-metadata" . | indent 4 }}
    spec:
    {{- include "kafka-app.pod-spec" . | indent 4 }}
      containers:
        {{- include "kafka-app.kafka-container" . | nindent 8 }}
          env:
          {{- include "kafka-app.common-env" . | nindent 12 }}
          {{- range .Values.ports }}
            {{- if .servicePort }} # TODO verify that there is at most one service port. Currently, if there are multiple service ports, the first one will be used
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KAFKA_APPLICATION_SERVER
              value: "$(POD_IP):{{ .containerPort }}"
            {{- end }}
          {{- end }}
          {{- include "kafka-app.group-instance-id-env" . | indent 12 }}
          {{- include "kafka-app.input-env" . | indent 12 }}
          {{- include "kafka-app.output-env" . | indent 12 }}
          {{- include "kafka-app.error-env" . | indent 12 }}
          {{- include "kafka-app.group-id-env" . | indent 12 }}
            - name: JAVA_TOOL_OPTIONS
              value: '{{ include "kafka-app.java-tool-jmx-options" . }}
                {{ include "kafka-app.java-tool-options" . }}'
        {{- if or (.Values.files) (and .Values.persistence.enabled .Values.statefulSet) (.Values.secretFilesRefs) }}
          volumeMounts:
            {{- include "kafka-app.volume-mounts" . | indent 12 }}
            {{- if and .Values.persistence.enabled .Values.statefulSet }}
            - name: datadir
              mountPath: /tmp/kafka-streams
            {{- end }}
        {{- end }}
        {{- if or (.Values.jmx.enabled) (.Values.ports) }}
          ports:
            {{- include "kafka-app.ports" . | indent 12 }}
            {{- include "kafka-app.jmx-port" . | indent 12 }}
        {{- end }}
      {{- if .Values.prometheus.jmx.enabled }}
      {{- include "kafka-app.prometheus-container" . | nindent 8 }}
      {{- end }}
      {{- if or (.Values.prometheus.jmx.enabled) (.Values.files) (.Values.secretFilesRefs) }}
      volumes:
        {{- include "kafka-app.jmx-volume" . | indent 8 }}
        {{- include "kafka-app.volumes" . | indent 8 }}
      {{- end }}
